### importing data 

In [58]:
import numpy as np
import pandas as pd
from sklearn import preprocessing as pp
from sklearn.ensemble import GradientBoostingRegressor
data = np.loadtxt("training_ccpp_x_y_train.csv",delimiter=",")
xtest = np.loadtxt("test_ccpp_x_test.csv",delimiter=",")
print(data)

[[   8.58   38.38 1021.03   84.37  482.26]
 [  21.79   58.2  1017.21   66.74  446.94]
 [  16.64   48.92 1011.55   78.76  452.56]
 ...
 [  29.8    69.34 1009.36   64.74  437.65]
 [  16.37   54.3  1017.94   63.63  459.97]
 [  30.11   62.04 1010.69   47.96  444.42]]


#### fetching x and y

In [59]:
x = data[:,0:4]
y = data[:,4]

## TODO

In [65]:
gbr = GradientBoostingRegressor(learning_rate=0.1) #1
scaler = pp.StandardScaler() #2
scaler.fit(x) # 3
x = scaler.transform(x) #4
scaler.fit(xtest)
xtest = scaler.transform(xtest)
gbr.fit(x,y) #5
y_pred  = gbr.predict(xtest) #6
np.savetxt('ypred_final.csv',y_pred, fmt='%1.5f') #7