In [32]:
# numpy definantion
# A library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, 
# along with a large collection of high-level mathematical functions to operate on these arrays.
import numpy as np
#splicing in multidimensional array
arr=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(arr)

In [3]:
np.shape(arr) # tells the shape of array created here it is 3*3

(3, 3)

In [12]:
arr[0] # Accessing rows

[1, 2, 3]

In [10]:
arr[:0]

[]

In [17]:
np.array(arr,dtype=complex)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [20]:
# we can create multidimenidal array of different size with passing dtype=object 
arr=[[1,2,3],[4,5,6],[7,8]]
np.array(arr,dtype=object)

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8])], dtype=object)

In [22]:
arr[2][1] 

8

In [28]:
#slicing in numpy arrayx
arr[0:2,0] 

array([1, 4])

In [35]:
# numpy arrange
# np.arange([start,]stop, [step,]dtype=None)
np.arange(3,10,2)

array([3, 5, 7, 9])

In [40]:
# NUMPY OPERATIONS
a1=np.array([1,2,3])
a2=np.array([10,20,30])
a1.sum()
a1.mean()
# returns dot prodict of a1 and a2
a1.dot(a2)
# it does element wise operation tat means it will add 2 to each element of array
a1+2 #similarly product and divide


array([3, 4, 5])

In [45]:
#numpy matrices use np.mat they are fixed 2d arrays like if we do 
a1=np.mat([[1,2],[3,4]])
a2=np.mat([[10,20],[4,5]])
a1*a2

matrix([[18, 30],
        [46, 80]])

In [46]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 3, 4, 5])
a.dot(b)

26

In [47]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

TypeError: cannot unpack non-iterable int object